// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import http from 'k6/http';

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  const url = "http://localhost:3000/api/user/search";
  const data = { first_name: 'Лев',  second_name :'Абрамов'};
  let res = http.request('GET', url, JSON.stringify(data), {    headers: { 'Content-Type': 'application/json' },   }); 
//  postman[Request]({
//    name: "http://localhost:3000/api/user/search",
//    id: "cd5724b9-2482-4c3f-849d-866121de9c11",
//    method: "GET",
//    address: "http://localhost:3000/api/user/search",
//    data: "data example",
//    data: '{\r\n    "first_name":"Лев",\r\n    "second_name":"Абрамов"\r\n}',
//    headers: {
//      Content-Type: "application/json",
//      jwt: "eyJhbGciOiJIUzI1NiJ9.NGRhZTk2NzctMjM0ZC00Yzc2LWIyMjItNDA3NjZhY2UxOTM0.YF9Dy56pIYwOocxo7EAvcdnNggfEPLoiehnmnnQP9BY"
//    }
//  });
}
